# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

jobs:
- job: "Quinoa"
  timeoutInMinutes: 180
  pool:
    vmImage: 'Ubuntu 16.04'
  variables:
    imageName: 'quinoa-azure:$(build.buildId)'
  strategy:
    matrix:
      gnu-debug:
        COMPILER: 'gnu'
        BUILD: 'Debug'
        DISTRO: 'debian-gnu'
      gnu-debug-static:
        COMPILER: 'gnu'
        BUILD: 'Debug'
        SHARED_LIBS: 'off'
        DISTRO: 'debian-gnu-static'
      gnu-release:
        COMPILER: 'gnu'
        BUILD: 'Release'
        DISTRO: 'debian-gnu'
      gnu-release-static:
        COMPILER: 'gnu'
        BUILD: 'Release'
        SHARED_LIBS: 'off'
        DISTRO: 'debian-gnu-static'
      gnu-debug-smp:
        COMPILER: 'gnu'
        BUILD: 'Debug'
        DISTRO: 'debian-gnu-smp'
        SMP: 'on'
      gnu-release-smp:
        COMPILER: 'gnu'
        BUILD: 'Release'
        DISTRO: 'debian-gnu-smp'
        SMP: 'on'
      clang-debug:
        COMPILER: 'clang'
        BUILD: 'Debug'
        DISTRO: 'debian-clang'
      clang-debug-static:
        COMPILER: 'clang'
        BUILD: 'Debug'
        SHARED_LIBS: 'off'
        DISTRO: 'debian-clang-static'
      clang-release:
        COMPILER: 'clang'
        BUILD: 'Release'
        DISTRO: 'debian-clang'
      clang-release-static:
        COMPILER: 'clang'
        BUILD: 'Release'
        SHARED_LIBS: 'off'
        DISTRO: 'debian-clang-static'
      clang-debug-smp:
        COMPILER: 'clang'
        BUILD: 'Debug'
        DISTRO: 'debian-clang-smp'
        SMP: 'on'
      clang-release-smp:
        COMPILER: 'clang'
        BUILD: 'Release'
        DISTRO: 'debian-clang-smp'
        SMP: 'on'
      doc:
        DOC: true
        DISTRO: 'debian-doc'
  steps:
    - bash: |
        cp -vr tools/docker $(HOME)/docker
        sed -i "/^FROM/s/debian/${DISTRO}/" docker/Dockerfile.quinoa-build-azure
        docker build \
               --build-arg COMPILER=${COMPILER} \
               --build-arg BUILD=${BUILD} \
               --build-arg DOC=${DOC} \
               --build-arg SHARED_LIBS="${SHARED_LIBS}" \
               --build-arg SMP=${SMP} \
               --rm=false -f docker/Dockerfile.quinoa-build-azure -t ${DISTRO} .
      displayName: 'Build & Test'
