language: cpp

sudo: required

services:
- docker

git:
  depth: false
  submodules: false

env:
  matrix:
    - DISTRO=debian BUILD_TYPE=Debug
                    TPL_DIR=/home/quinoa/tpl/gnu
                    CXXFLAGS=-Werror
                    MPICC=mpicc
                    MPICXX=mpicxx
                    DOCKERHUB=true
    - DISTRO=debian BUILD_TYPE=Release
                    TPL_DIR=/home/quinoa/tpl/gnu
                    CXXFLAGS=-Werror
                    MPICC=mpicc
                    MPICXX=mpicxx
                    DOCKERHUB=true
    - DISTRO=debian BUILD_TYPE=Debug
                    TPL_DIR=/home/quinoa/tpl/clang
                    CXXFLAGS="-Wno-unknown-argument -Werror"
                    MPICC=/opt/openmpi/bin/mpicc
                    MPICXX=/opt/openmpi/bin/mpicxx
                    DOCKERHUB=true
    - DISTRO=debian BUILD_TYPE=Release
                    TPL_DIR=/home/quinoa/tpl/clang
                    CXXFLAGS="-Wno-unknown-argument -Werror"
                    MPICC=/opt/openmpi/bin/mpicc
                    MPICXX=/opt/openmpi/bin/mpicxx
                    DOCKERHUB=true
    - DISTRO=alpine SONARQUBE=ON
                    COVERAGE=ON
                    TPL_DIR=/home/quinoa/tpl
                    CXXFLAGS=-Werror
                    MPICC=mpicc
                    MPICXX=mpicxx
                    BUILD_TYPE=Debug
                    RUNNER_ARGS="-mca plm isolated"
                    DOCKERHUB=true

script:
  - export CC=${MPICC}
  - export CXX=${MPICXX}
  - rm -rf tpl
  - cp -vr docker ${HOME}/docker
  - sed -i "/^FROM/s/debian/${DISTRO}/" ${HOME}/docker/Dockerfile.quinoa-build-travis
  - cd ../../
  - mv -v ${TRAVIS_REPO_SLUG} $HOME/docker/quinoa
  - cp -r $HOME/.sonar ${HOME}/docker/sonar
  - docker build --build-arg CXXFLAGS="${CXXFLAGS}"
                 --build-arg COVERAGE=${COVERAGE}
                 --build-arg FC=${FC} --build-arg CC=${CC} --build-arg CXX=${CXX}
                 --build-arg RUNNER_ARGS="${RUNNER_ARGS}"
                 --build-arg TPL_DIR="${TPL_DIR}"
                 --build-arg SONARQUBE=${SONARQUBE}
                 --build-arg SONARQUBE_TOKEN=${SONARQUBE_TOKEN}
                 --build-arg SONARQUBE_GITHUB_TOKEN=${SONARQUBE_GITHUB_TOKEN}
                 --build-arg TRAVIS_BRANCH=${TRAVIS_BRANCH}
                 --build-arg TRAVIS_JOB_NUMBER=${TRAVIS_JOB_NUMBER}
                 --build-arg TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}
                 --build-arg TRAVIS_JOB_ID=${TRAVIS_JOB_ID}
                 --build-arg TRAVIS_TAG=${TRAVIS_TAG}
                 --build-arg TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG}
                 --build-arg TRAVIS_COMMIT=${TRAVIS_COMMIT}
                 -t ${TRAVIS_REPO_SLUG}:${DISTRO}
                 -f ${HOME}/docker/Dockerfile.quinoa-build-travis
                 ${HOME}/docker/ &&
    CON=$(docker run -d ${TRAVIS_REPO_SLUG}:${DISTRO} /bin/bash) &&
    docker cp ${CON}:/home/quinoa/.sonar ${HOME}/

after_success:
  - if [[ ${DOCKERHUB} = true && ${DOCKER_USERNAME} && ${DOCKER_PASSWORD} && ${TRAVIS_PULL_REQUEST} == false && ${TRAVIS_BRANCH} == master ]]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push "${TRAVIS_REPO_SLUG}:${DISTRO}";
    fi

cache:
  directories:
    - $HOME/.sonar

notifications:
  email:
    recipients:
      secure: UwVJfZCCdmyJafVDJ2E9T8H1b/24y+9HjQp/CiQKROM5F26YgilTuMjeqd7MXV2UKWvnKI7oZudWd3ldxCr8LbJhEBxK8lZVQeFdbWWOpD2t6rXh9SaLIXcpDXgitegpyMP2vq7ED7JcxICaxAd/Gb+84SUY+rSxRbG99CzV4gwsspL1TLUY49pPFRzrDL9amp2qXv/RRQzihM7Yeo7aIL+dYcB/keaFw1MT8unLzWj69BON2HCMF5JfLp84pvTzNvKNI8sN+cc4rTQYqrLH0bFOXMKlqMJqAC6tKDlPKkqjIr01lKSFWbwTxyaz8JcaFQX/WzCFVmLqEs700oZmUI27SOQ1Jj85o9uYgyjmHN5r+mktmGtZ3aMiPIiXyh3nPzrsdh8RbzHf33JnSh6t5Gk0jvhjWbFnQIwqFr4ebfCPvwlx9hvDlzhEOLgfvgAmajwn6TrmYbO/zFugWoGXVEH0OBd4sIchhiXum6VuDYdlDCW+TsXMEtzhKKiABbTRBfqcCOQcPNhSNdM2Vrpax4FTDndvvd25L2RfcygaXhSczOsHWom+MnEQCIkPPIqkaj+tkb8br5sLnYWIsoZ/uD1f+bnTwlnwWixOXQx1nkjafSixx8uEm5nmALzL4KnEHu4xslSwa85asMH730W/untnABbh6/WmMYivsD029Wo=
